"""add submissions table

Revision ID: 182c176387cd
Revises: 6f737d1a732f
Create Date: 2026-09-30 21:41:12.103522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '182c176387cd'
down_revision: Union[str, Sequence[str], None] = '6f737d1a732f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('submission_id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('ecr_id', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submissions_case_id'), 'submissions', ['case_id'], unique=False)
    op.create_index(op.f('ix_submissions_ecr_id'), 'submissions', ['ecr_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_ecr_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_case_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
