"""add patient names

Revision ID: 426cd7367e7e
Revises: ac44418049d5
Create Date: 2026-09-29 16:54:08.581327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426cd7367e7e'
down_revision: Union[str, Sequence[str], None] = 'ac44418049d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    # ### end Alembic commands ###
