"""add cases table

Revision ID: 6f737d1a732f
Revises: 426cd7367e7e
Create Date: 2026-09-30 18:41:31.405427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f737d1a732f'
down_revision: Union[str, Sequence[str], None] = '426cd7367e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('patient', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('facility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('clinical_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('laboratory_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction_status', sa.String(length=50), nullable=False),
    sa.Column('reportability_decision', sa.String(length=50), nullable=False),
    sa.Column('reportability_evidence_status', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('final_decision', sa.String(length=50), nullable=True),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_candidate_id'), 'cases', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_cases_disease'), 'cases', ['disease'], unique=False)
    op.create_index(op.f('ix_cases_jurisdiction'), 'cases', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_jurisdiction'), table_name='cases')
    op.drop_index(op.f('ix_cases_disease'), table_name='cases')
    op.drop_index(op.f('ix_cases_candidate_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
