"""initial signal schema

Revision ID: ac44418049d5
Revises:
Create Date: 2026-09-28 20:09:06.542448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac44418049d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('source_patient_id', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=30), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_resource', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('source', 'source_patient_id', name='uq_patient_source_id')
    )
    op.create_index(op.f('ix_patients_source'), 'patients', ['source'], unique=False)
    op.create_index(op.f('ix_patients_source_patient_id'), 'patients', ['source_patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('source_encounter_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.String(length=255), nullable=True),
    sa.Column('encounter_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_resource', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('encounter_id'),
    sa.UniqueConstraint('source', 'source_encounter_id', name='uq_encounter_source_id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_source'), 'encounters', ['source'], unique=False)
    op.create_index(op.f('ix_encounters_source_encounter_id'), 'encounters', ['source_encounter_id'], unique=False)
    op.create_table('clinical_documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_status', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_reference', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_location', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_resource', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('source', 'source_document_id', name='uq_clinical_document_source_id')
    )
    op.create_index(op.f('ix_clinical_documents_encounter_id'), 'clinical_documents', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_clinical_documents_patient_id'), 'clinical_documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_documents_source'), 'clinical_documents', ['source'], unique=False)
    op.create_index(op.f('ix_clinical_documents_source_document_id'), 'clinical_documents', ['source_document_id'], unique=False)
    op.create_table('conditions',
    sa.Column('condition_id', sa.Uuid(), nullable=False),
    sa.Column('source_condition_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('condition_code', sa.String(length=100), nullable=True),
    sa.Column('condition_system', sa.String(length=255), nullable=True),
    sa.Column('condition_display', sa.Text(), nullable=True),
    sa.Column('clinical_status', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=100), nullable=True),
    sa.Column('onset_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_resource', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('condition_id'),
    sa.UniqueConstraint('source', 'source_condition_id', name='uq_condition_source_id')
    )
    op.create_index(op.f('ix_conditions_condition_code'), 'conditions', ['condition_code'], unique=False)
    op.create_index(op.f('ix_conditions_encounter_id'), 'conditions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conditions_source'), 'conditions', ['source'], unique=False)
    op.create_index(op.f('ix_conditions_source_condition_id'), 'conditions', ['source_condition_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('lab_result_id', sa.Uuid(), nullable=False),
    sa.Column('source_lab_result_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('test_code', sa.String(length=100), nullable=True),
    sa.Column('test_system', sa.String(length=255), nullable=True),
    sa.Column('test_display', sa.Text(), nullable=True),
    sa.Column('report_status', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('effective_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performer_reference', sa.String(length=255), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_resource', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lab_result_id'),
    sa.UniqueConstraint('source', 'source_lab_result_id', name='uq_lab_result_source_id')
    )
    op.create_index(op.f('ix_lab_results_encounter_id'), 'lab_results', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_results_source'), 'lab_results', ['source'], unique=False)
    op.create_index(op.f('ix_lab_results_source_lab_result_id'), 'lab_results', ['source_lab_result_id'], unique=False)
    op.create_index(op.f('ix_lab_results_test_code'), 'lab_results', ['test_code'], unique=False)
    op.create_table('observations',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('source_observation_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('observation_code', sa.String(length=100), nullable=True),
    sa.Column('observation_system', sa.String(length=255), nullable=True),
    sa.Column('observation_display', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('value_numeric', sa.Numeric(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('value_system', sa.String(length=255), nullable=True),
    sa.Column('value_code', sa.String(length=100), nullable=True),
    sa.Column('effective_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_resource', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id'),
    sa.UniqueConstraint('source', 'source_observation_id', name='uq_observation_source_id')
    )
    op.create_index(op.f('ix_observations_encounter_id'), 'observations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_observations_observation_code'), 'observations', ['observation_code'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_observations_source'), 'observations', ['source'], unique=False)
    op.create_index(op.f('ix_observations_source_observation_id'), 'observations', ['source_observation_id'], unique=False)
    op.create_table('lab_result_observations',
    sa.Column('lab_result_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lab_result_id'], ['lab_results.lab_result_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.observation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lab_result_id', 'observation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_result_observations')
    op.drop_index(op.f('ix_observations_source_observation_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_source'), table_name='observations')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_code'), table_name='observations')
    op.drop_index(op.f('ix_observations_encounter_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_lab_results_test_code'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_source_lab_result_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_source'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_encounter_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_conditions_source_condition_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_source'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_encounter_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_condition_code'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_clinical_documents_source_document_id'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_source'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_patient_id'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_encounter_id'), table_name='clinical_documents')
    op.drop_table('clinical_documents')
    op.drop_index(op.f('ix_encounters_source_encounter_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_source'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_patients_source_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_source'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
