from datetime import datetime, timezone
from typing import Any, Dict

from fastapi import FastAPI, Header, HTTPException
from datetime import datetime, timezone

from app.ingestion.fhir.normalizer import normalize_bundle
from app.detection.candidate_service import detect_candidates


app = FastAPI(
    title="SIGNAL FHIR Ingestion API",
    description="FHIR ingestion and candidate detection service for SIGNAL",
    version="1.0.0",
)


@app.get("/")
def root():
    return {
        "service": "SIGNAL FHIR Ingestion API",
        "status": "running",
        "version": "1.0.0",
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


@app.post("/api/ingestion/fhir")
def ingest_fhir(
    bundle: Dict[str, Any],
    source_system: str | None = Header(
        default=None,
        alias="X-Source-System"
    ),
    fhir_version: str | None = Header(
        default=None,
        alias="X-FHIR-Version"
    ),
):
    """
    Receive a FHIR Bundle and normalize it.

    Provenance is supplied through HTTP headers.
    The ingestion timestamp is generated by the API.
    """

    try:

        # --------------------------------------------------
        # Validate FHIR Bundle
        # --------------------------------------------------

        if bundle.get("resourceType") != "Bundle":
            raise HTTPException(
                status_code=400,
                detail="Input must be a FHIR Bundle."
            )

        entries = bundle.get(
            "entry",
            []
        )

        if not isinstance(entries, list):
            raise HTTPException(
                status_code=400,
                detail="FHIR Bundle entry must be a list."
            )

        # --------------------------------------------------
        # Group FHIR resources
        # --------------------------------------------------

        resources: Dict[
            str,
            list[Dict[str, Any]]
        ] = {}

        for entry in entries:

            if not isinstance(entry, dict):
                raise HTTPException(
                    status_code=400,
                    detail=(
                        "FHIR Bundle entry "
                        "must be a valid object."
                    )
                )

            resource = entry.get(
                "resource"
            )

            if not isinstance(resource, dict):
                raise HTTPException(
                    status_code=400,
                    detail=(
                        "FHIR Bundle entry "
                        "must contain a valid resource."
                    )
                )

            resource_type = resource.get(
                "resourceType"
            )

            if not resource_type:
                raise HTTPException(
                    status_code=400,
                    detail="FHIR resourceType is missing."
                )

            resources.setdefault(
                resource_type,
                []
            ).append(resource)

        # --------------------------------------------------
        # Build dynamic provenance
        # --------------------------------------------------

        provenance = {
            "source_system": source_system,
            "source_format": "FHIR",
            "fhir_version": fhir_version,
            "ingested_at": datetime.now(
                timezone.utc
            ).isoformat(),
        }

        # --------------------------------------------------
        # Normalize FHIR resources
        # --------------------------------------------------

        normalized = normalize_bundle(
            resources,
            provenance=provenance
        )

        # --------------------------------------------------
        # API response
        # --------------------------------------------------

        return {
            "status": "success",
            "message": (
                "FHIR Bundle ingested and "
                "normalized successfully."
            ),
            "data": normalized,
        }

    except HTTPException:
        raise

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=(
                f"FHIR normalization failed: {str(exc)}"
            )
        )


@app.post("/api/detection/candidates")
def detect_candidate_endpoint(
    normalized_patient: Dict[str, Any],
    triggers: list[Dict[str, Any]] | None = None,
):
    """
    Detect potential public-health candidates from normalized
    clinical data using configured structured triggers.
    """

    try:

        result = detect_candidates(
            normalized_patient=normalized_patient,
            triggers=triggers,
        )

        return {
            "status": "success",
            "message": (
                "Candidate detection completed successfully."
            ),
            "data": result,
        }

    except ValueError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        )

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=(
                f"Candidate detection failed: {str(exc)}"
            ),
        )