from __future__ import annotations

from typing import Any, Dict, List, Tuple


def _fusion_key(signal: Dict[str, Any]) -> Tuple[Any, Any, Any]:
    """
    Identify signals that may refer to the same potential
    clinical event.

    Current MVP key:
        patient + encounter + disease

    This is candidate correlation, not reportability logic.
    """

    return (
        signal.get("patient_id"),
        signal.get("encounter_id"),
        signal.get("disease_id"),
    )


def _create_candidate(
    signals: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Combine multiple candidate signals into one unified candidate.
    """

    first_signal = signals[0]

    evidence = [
        signal.get("evidence", {})
        for signal in signals
    ]

    confidence_values = [
        signal.get("confidence")
        for signal in signals
        if isinstance(signal.get("confidence"), (int, float))
    ]

    confidence = (
        max(confidence_values)
        if confidence_values
        else None
    )

    return {
        "patient_id": first_signal.get("patient_id"),
        "encounter_id": first_signal.get("encounter_id"),
        "disease_id": first_signal.get("disease_id"),
        "status": "POTENTIAL",
        "trigger_type": first_signal.get("trigger_type"),
        "evidence": evidence,
        "confidence": confidence,
        "detected_at": first_signal.get("detected_at"),
        "signals": signals,
    }


def fuse_candidate_signals(
    signals: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Fuse candidate signals referring to the same potential event.

    Input:
        Candidate signals generated by detection agents.

    Output:
        Unified potential candidates.

    This function does NOT:
        - determine jurisdiction
        - determine reportability
        - confirm a case
        - create an eCR
        - submit a report
    """

    if not isinstance(signals, list):
        raise ValueError("signals must be a list.")

    groups: Dict[
        Tuple[Any, Any, Any],
        List[Dict[str, Any]]
    ] = {}

    for signal in signals:

        if not isinstance(signal, dict):
            continue

        key = _fusion_key(signal)

        groups.setdefault(key, []).append(signal)

    candidates = [
        _create_candidate(group)
        for group in groups.values()
        if group
    ]

    return candidates