import { useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { Activity, ArrowRight, CheckCircle2, ShieldCheck } from 'lucide-react'
import { governanceService, outcomeLearningService } from '../services/aiGovernanceService.js'

function useLoad(loader, dependencies = []) {
  const [data,setData]=useState(null)
  // Callers pass the values that determine each request; inline loader closures are intentionally excluded.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{let alive=true;loader().then(value=>alive&&setData(value));return()=>{alive=false}},dependencies)
  return data
}
const demo=<div className="demo-note"><span/> Demo / Synthetic Data · Not production measurements</div>
const governanceLinks=[['Overview','/governance'],['AI Monitoring','/governance/monitoring'],['Model Evaluation','/governance/evaluation'],['Explainability','/governance/explainability'],['Agent Governance','/governance/agents'],['Outcome Learning','/governance/outcome-learning']]
function GovLayout({title,sub,children}) { const {pathname}=useLocation();return <div className="page"><div className="page-heading"><div><h1>{title}</h1><p>{sub}</p></div></div>{demo}<div className="gov-tabs">{governanceLinks.map(([name,path])=><Link key={path} to={path} className={pathname===path?'selected':''}>{name}</Link>)}</div>{children}</div> }
function Metric({label,value,note}) { return <div className="metric-card"><span>{label}</span><strong>{value ?? '—'}</strong><small>{note}</small><Activity className="metric-spark" size={18}/></div> }
function Status({children}) { const raw=children || 'Not available',normalized=String(raw).toLowerCase().replaceAll(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');return <span className={`badge ${normalized}`}>{raw}</span> }
function Table({headers,children}) { return <div className="panel"><div className="table-wrapper"><table><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div> }
const dateTime=value=>value?new Date(value).toLocaleString(): 'Not available'
const agentName=(agents,id)=>agents?.find(agent=>agent.agent_id===id)?.name || id || 'Not specified'
const field=(value)=>value===undefined||value===null||value===''?'Not available':String(value)

export function GovernanceOverview() {
  const d=useLoad(()=>governanceService.getGovernanceOverview(),[]),agents=useLoad(()=>governanceService.getAgents(),[])
  return <GovLayout title="AI Governance Overview" sub="Centralized visibility across the SIGNAL AI layer."><div className="metrics-grid gov-metrics"><Metric label="REGISTERED AGENTS" value={d?.registered_agents} note="Agent registry"/><Metric label="ACTIVE AGENTS" value={d?.active_agents} note="Across SIGNAL AI layer"/><Metric label="RECENT EXECUTIONS" value={d?.recent_executions} note="Demo event records"/><Metric label="EXECUTION FAILURES" value={d?.execution_failures} note="Demo event records"/><Metric label="EVALUATION RUNS" value={d?.evaluation_runs} note="Synthetic runs"/><Metric label="AGENTS REQUIRING REVIEW" value={d?.agents_requiring_review} note="Based on registry status"/><Metric label="EXPLAINABILITY TRACES" value={d?.explainability_coverage} note="Available demo traces"/><Metric label="OUTCOME SIGNALS" value={d?.outcome_learning_signals} note="Historical demo records"/></div><section className="panel"><div className="panel-header"><div><h3>SIGNAL AI Layer</h3><p>Registered agents and current governance state.</p></div></div><div className="ai-architecture">{(agents||[]).map(agent=><Link to={`/governance/agents/${agent.agent_id}`} className="agent-card" key={agent.agent_id}><b>{agent.name}</b><p>{agent.purpose || agent.description || 'Purpose not provided'}</p><div><Status>{agent.status || 'Not specified'}</Status><small>{agent.version?`v${agent.version}`:'Version unavailable'}</small></div></Link>)}</div></section><section className="panel pad gov-callout"><ShieldCheck/><div><b>Cross-cutting governance</b><p>Monitoring, evaluation, explainability, agent governance, and Outcome Learning observe AI activities across the reporting process. They are separate from the candidate reporting workflow.</p></div></section></GovLayout>
}

export function MonitoringPage() {
  const agents=useLoad(()=>governanceService.getAgents(),[]),[filters,setFilters]=useState({agent_id:'',status:'',agent_version:'',candidate_id:'',started_after:'',started_before:''})
  const executions=useLoad(()=>governanceService.getExecutions(filters),[filters]),rows=executions||[],success=rows.filter(row=>row.status==='SUCCESS').length,failed=rows.filter(row=>row.status==='FAILURE').length,latencies=rows.map(row=>row.latency_ms).filter(Number.isFinite),average=latencies.length?`${(latencies.reduce((sum,n)=>sum+n,0)/latencies.length/1000).toFixed(2)}s`:'Not available'
  const update=(key,value)=>setFilters(current=>({...current,[key]:value}))
  return <GovLayout title="AI Monitoring" sub="Generic execution events across registered SIGNAL AI agents."><div className="metrics-grid gov-metrics"><Metric label="TOTAL EXECUTIONS" value={rows.length} note="Matching filters · demo events"/><Metric label="SUCCESSFUL" value={success} note="Execution status"/><Metric label="FAILED EXECUTIONS" value={failed} note="Execution status"/><Metric label="AVERAGE LATENCY" value={average} note="From available event latency"/><Metric label="AGENTS REGISTERED" value={agents?.length ?? '—'} note="Agent registry"/></div><section className="panel pad gov-filters"><label>Agent<select value={filters.agent_id} onChange={event=>update('agent_id',event.target.value)}><option value="">All agents</option>{(agents||[]).map(agent=><option key={agent.agent_id} value={agent.agent_id}>{agent.name}</option>)}</select></label><label>Status<select value={filters.status} onChange={event=>update('status',event.target.value)}><option value="">All statuses</option><option>SUCCESS</option><option>FAILURE</option></select></label><label>Version<input value={filters.agent_version} onChange={event=>update('agent_version',event.target.value)} placeholder="Any version"/></label><label>Candidate ID<input value={filters.candidate_id} onChange={event=>update('candidate_id',event.target.value)} placeholder="Any candidate"/></label><label>Started after<input type="datetime-local" value={filters.started_after} onChange={event=>update('started_after',event.target.value)}/></label><label>Started before<input type="datetime-local" value={filters.started_before} onChange={event=>update('started_before',event.target.value)}/></label></section><Table headers={['Execution','Agent','Version','Candidate','Status','Started','Latency','Model','Input Source','Output Type','Error']}>{rows.map(row=><tr key={row.execution_id}><td>{row.execution_id}</td><td><Link to={`/governance/agents/${row.agent_id}`}>{agentName(agents,row.agent_id)}</Link></td><td>{field(row.agent_version)}</td><td>{field(row.candidate_id)}</td><td><Status>{row.status}</Status></td><td>{dateTime(row.started_at)}</td><td>{row.latency_ms==null?'Not available':`${row.latency_ms} ms`}</td><td>{field(row.model)}</td><td>{field(row.input_source)}</td><td>{field(row.output_type)}</td><td>{row.error||'—'}</td></tr>)}</Table>{!rows.length&&<div className="note">No execution events match these filters.</div>}</GovLayout>
}

export function EvaluationPage() {
  const agents=useLoad(()=>governanceService.getAgents(),[]),runs=useLoad(()=>governanceService.getEvaluations(),[])
  return <GovLayout title="Model Evaluation" sub="Evaluation runs associated with registered agents, models, versions, and datasets."><p className="note">Demo / Synthetic Evaluation Data. These values do not represent production performance.</p><Table headers={['Evaluation Run','Agent','Model','Version','Dataset','Timestamp','Metrics','Data Type']}>{(runs||[]).map(run=><tr key={run.evaluation_run_id}><td>{run.evaluation_run_id}</td><td><Link to={`/governance/agents/${run.agent_id}`}>{agentName(agents,run.agent_id)}</Link></td><td>{field(run.model)}</td><td>{field(run.version)}</td><td>{field(run.dataset)}</td><td>{dateTime(run.timestamp)}</td><td>{run.metrics?Object.entries(run.metrics).map(([name,value])=><span key={name} className="metric-inline">{name}: {Number(value).toFixed(2)} </span>):'Evaluation metrics unavailable'}</td><td>{run.synthetic?'Demo / Synthetic':'Evaluation data'}</td></tr>)}</Table>{!runs?.length&&<div className="note">Evaluation data not available.</div>}<div className="note">Metrics are task-specific. No production evaluation measurements are available in this demo.</div></GovLayout>
}

export function ExplainabilityPage() {
  const traces=useLoad(()=>governanceService.getEvidenceTraces(),[]),agents=useLoad(()=>governanceService.getAgents(),[]),[candidate,setCandidate]=useState('')
  const trace=traces?.find(item=>item.candidate_id===candidate)||traces?.[0]
  return <GovLayout title="Explainability" sub="Trace AI-supported outputs to source evidence and human decisions, without exposing private model reasoning."><section className="panel pad gov-filters"><label>Candidate trace<select value={trace?.candidate_id||''} onChange={event=>setCandidate(event.target.value)}>{(traces||[]).map(item=><option key={item.candidate_id} value={item.candidate_id}>{item.candidate_id} · {item.execution_id}</option>)}</select></label></section>{trace?<><section className="panel"><div className="panel-header"><div><h3>Evidence Trace · {trace.candidate_id}</h3><p>Execution {trace.execution_id} · source-backed provenance</p></div><Status>{trace.human_decision?.status||'Pending human decision'}</Status></div><div className="trace-flow">{[{title:'Source',body:`${field(trace.source?.name)} · ${field(trace.source?.type)} · ${dateTime(trace.source?.timestamp)}`,ref:trace.source?.reference},...(trace.evidence||[]).map((item,index)=>({title:`Extracted Evidence ${index+1}`,body:item.text,ref:`${item.reference||'Reference unavailable'} · ${dateTime(item.timestamp)}`})),{title:'Agent',body:`${agentName(agents,trace.agent_id)} · v${field(trace.agent_version)}`,ref:trace.execution_id},{title:'AI Output',body:trace.output?.type,ref:trace.output?.reference},{title:'Human Verification',body:`${field(trace.human_decision?.status)} · ${field(trace.human_decision?.reviewer)} · ${dateTime(trace.human_decision?.timestamp)}`,ref:'Reviewer decision record'},{title:'Outcome',body:trace.outcome?.status,ref:trace.outcome?.reference}].map((item,index)=><div className="trace-item" key={`${item.title}-${index}`}><span>{String(index+1).padStart(2,'0')}</span><b>{item.title}</b><p>{item.body}</p><small>{item.ref||'Evidence reference unavailable'}</small></div>)}</div></section><Table headers={['Source','Type','Timestamp','Evidence Reference','Agent / Version','Execution','Candidate']}><tr><td>{field(trace.source?.name)}</td><td>{field(trace.source?.type)}</td><td>{dateTime(trace.source?.timestamp)}</td><td>{field(trace.source?.reference)}</td><td>{agentName(agents,trace.agent_id)} · {field(trace.agent_version)}</td><td>{trace.execution_id}</td><td>{trace.candidate_id}</td></tr></Table></>:<div className="panel pad">Evidence/provenance data not available.</div>}</GovLayout>
}

export function AgentGovernancePage() {
  const agents=useLoad(()=>governanceService.getAgents(),[]),audit=useLoad(()=>governanceService.getAuditEvents(),[])
  return <GovLayout title="Agent Governance" sub="Dynamic registry, ownership, status, and audit context for current and future agents."><Table headers={['Agent','Purpose','Version','Model','Status','Monitoring','Evaluation','Governance','Action']}>{(agents||[]).map(agent=><tr key={agent.agent_id}><td><Link to={`/governance/agents/${agent.agent_id}`}>{agent.name}</Link><small className="sub-cell">{agent.agent_id}</small></td><td>{agent.purpose||agent.description||'Not provided'}</td><td>{field(agent.version)}</td><td>{field(agent.model)}</td><td><Status>{agent.status||'Not specified'}</Status></td><td><Status>{agent.monitoring_status||'Not available'}</Status></td><td><Status>{agent.evaluation_status||'Not available'}</Status></td><td><Status>{agent.governance_status||'Not available'}</Status></td><td><Link className="text-link" to={`/governance/agents/${agent.agent_id}`}>View Details <ArrowRight size={13}/></Link></td></tr>)}</Table><AuditPanel rows={audit||[]} agents={agents||[]}/></GovLayout>
}

function AuditPanel({rows,agents}) { return <section className="panel audit-panel"><div className="panel-header"><div><h3>Governance Audit History</h3><p>Execution and human oversight events</p></div></div>{rows.map(event=><div className="source-row" key={`${event.execution_id}-${event.action}`}><b>{dateTime(event.timestamp)} · {event.action}</b><span>{agentName(agents,event.agent_id)} v{field(event.agent_version)} · {event.execution_id} · {event.candidate_id}</span><small>{event.actor} · {event.detail}</small></div>)}</section> }

export function AgentDetailPage() {
  const {agentId}=useParams(),agent=useLoad(()=>governanceService.getAgent(agentId),[agentId]),executions=useLoad(()=>governanceService.getExecutions({agent_id:agentId}),[agentId]),evaluations=useLoad(()=>governanceService.getEvaluations({agent_id:agentId}),[agentId]),audit=useLoad(()=>governanceService.getAuditEvents({agent_id:agentId}),[agentId]),[tab,setTab]=useState('Monitoring')
  if(agent===null)return <GovLayout title="Agent Details" sub="Agent is not registered."><Link to="/governance/agents">Return to Agent Governance</Link></GovLayout>
  if(!agent)return <GovLayout title="Agent Details" sub="Loading registered agent…"/>
  const issues=(executions||[]).filter(item=>item.status==='FAILURE')
  return <GovLayout title="Agent Details" sub={agent.name}><section className="panel pad agent-detail"><div className="panel-header"><div><h3>{agent.name}</h3><p>{agent.description||agent.purpose||'Description not provided'}</p></div><Status>{agent.status||'Not specified'}</Status></div><div className="info-grid">{[['AGENT ID',agent.agent_id],['PURPOSE',agent.purpose],['VERSION',agent.version],['MODEL',agent.model],['OWNER',agent.owner],['MONITORING',agent.monitoring_status],['EVALUATION',agent.evaluation_status],['GOVERNANCE',agent.governance_status]].map(([label,value])=><div className="info" key={label}><small>{label}</small><b>{field(value)}</b></div>)}</div></section><div className="gov-tabs detail-tabs">{['Recent Executions','Evaluation Runs','Recent Issues','Audit Information'].map(name=><button className={tab===name?'selected':''} onClick={()=>setTab(name)} key={name}>{name}</button>)}</div><section className="panel pad"><div className="panel-header"><div><h3>{tab}</h3><p>Records linked to {agent.agent_id} · Demo data</p></div></div>{tab==='Recent Executions'?<div className="agent-event-list">{(executions||[]).map(item=><div className="source-row" key={item.execution_id}><b>{item.execution_id} · {item.status}</b><span>{item.candidate_id||'Candidate not linked'} · {item.agent_version||'Version unavailable'} · {item.latency_ms??'—'} ms</span><small>{dateTime(item.started_at)} · {item.input_source||'Input unspecified'} → {item.output_type||'Output unspecified'}{item.error?` · ${item.error}`:''}</small></div>)}</div>:tab==='Evaluation Runs'?<div className="agent-event-list">{(evaluations||[]).length?(evaluations||[]).map(run=><div className="source-row" key={run.evaluation_run_id}><b>{run.evaluation_run_id} · {run.model||'Model unavailable'} v{run.version||'—'}</b><span>{run.dataset||'Dataset unavailable'} · {dateTime(run.timestamp)}</span><small>{run.metrics?Object.entries(run.metrics).map(([key,value])=>`${key}: ${value}`).join(' · '):'Evaluation data not available'} · Demo / Synthetic</small></div>):<p>Evaluation data not available for this agent.</p>}</div>:tab==='Recent Issues'?<div className="agent-event-list">{issues.length?issues.map(item=><div className="source-row" key={item.execution_id}><b>{item.execution_id} · {item.candidate_id||'Candidate not linked'}</b><span>{item.error||'Execution issue'}</span><small>{dateTime(item.started_at)} · {item.agent_version||'Version unavailable'}</small></div>):<p>No recent execution issues recorded.</p>}</div>:<div className="agent-event-list">{(audit||[]).length?(audit||[]).map(item=><div className="source-row" key={`${item.execution_id}-${item.action}`}><b>{item.action} · {item.actor}</b><span>{item.execution_id} · {item.candidate_id}</span><small>{dateTime(item.timestamp)} · {item.agent_version} · {item.detail}</small></div>):<p>No audit events recorded for this agent.</p>}</div>}</section></GovLayout>
}

export function OutcomeLearningPage() {
  const overview=useLoad(()=>outcomeLearningService.getOverview(),[]),rows=useLoad(()=>outcomeLearningService.getLearningSignals(),[]),agents=useLoad(()=>governanceService.getAgents(),[])
  return <GovLayout title="Outcome Learning" sub="Agent 44 · Historical decisions and PHA outcomes inform analysis and future evaluation."><section className="panel learning-flow"><div className="panel-header"><div><h3>Outcome Learning Feedback Loop</h3><p>Observed outcomes inform analytics and evaluation; they do not automatically update live models.</p></div></div><div className="trace-flow">{['AI Output','Clinical Staff Decision','Reporting Administrator Decision','PHA Outcome','Correction / Rejection Reason','Outcome Learning','Future Evaluation'].map((item,index)=><div className="trace-item" key={item}><span>{String(index+1).padStart(2,'0')}</span><b>{item}</b></div>)}</div></section><div className="metrics-grid gov-metrics"><Metric label="HISTORICAL SIGNALS" value={overview?.analyzed} note="Demo records"/><Metric label="CLINICAL DECISIONS RECORDED" value={overview?.feedback} note="Demo records"/><Metric label="PHA ACKNOWLEDGEMENTS" value={overview?.pha} note="Demo records"/><Metric label="SIGNALS UNDER REVIEW" value={overview?.analysis} note="Observed or under review"/></div><section className="panel"><div className="panel-header"><div><h3>Historical Feedback Signals</h3><p>AI output, staff and administrator decisions, PHA outcome, and correction reason where available.</p></div></div><div className="table-wrapper"><table><thead><tr>{['Candidate','Agent','AI Output','Clinical Staff','Reporting Admin','PHA Outcome','Correction Reason','Status','Action'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{(rows||[]).map(row=><tr key={row.id}><td>{row.candidate_id}</td><td>{agentName(agents,row.agent_id)}</td><td>{row.ai_output}</td><td>{row.clinical_staff_decision}</td><td>{row.reporting_admin_decision}</td><td>{row.pha_outcome}</td><td>{row.correction_reason||'—'}</td><td><Status>{row.status}</Status></td><td><Link className="text-link" to={`/governance/outcome-learning/${row.id}`}>View Signal <ArrowRight size={13}/></Link></td></tr>)}</tbody></table></div></section><div className="note">Signals are observed, reviewed, validated, or included in future evaluation. No automatic production model retraining is implemented.</div></GovLayout>
}

export function LearningSignalDetail() {
  const {signalId}=useParams(),signal=useLoad(()=>outcomeLearningService.getLearningSignal(signalId),[signalId]),agents=useLoad(()=>governanceService.getAgents(),[])
  if(!signal)return <GovLayout title="Learning Signal" sub="Loading outcome record…"/>
  return <GovLayout title="Learning Signal Detail" sub={`Agent 44 · ${signal.id}`}><section className="panel pad"><div className="panel-header"><div><h3>{signal.signal}</h3><p>{signal.candidate_id} · {dateTime(signal.timestamp)}</p></div><Status>{signal.status}</Status></div><div className="info-grid">{[['CANDIDATE',signal.candidate_id],['AGENT',agentName(agents,signal.agent_id)],['AI OUTPUT',signal.ai_output],['CLINICAL STAFF DECISION',signal.clinical_staff_decision],['REPORTING ADMIN DECISION',signal.reporting_admin_decision],['PHA OUTCOME',signal.pha_outcome],['CORRECTION / REJECTION REASON',signal.correction_reason||'None recorded'],['LEARNING STATUS',signal.status]].map(([label,value])=><div className="info" key={label}><small>{label}</small><b>{field(value)}</b></div>)}</div></section><div className="panel pad gov-callout"><CheckCircle2/><div><b>Outcome feedback record</b><p>This record supports analytics and future evaluation. It does not directly modify or retrain a production model.</p></div></div></GovLayout>
}
