import React, { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { SignalLoading } from "../components/ui/SignalLoading.jsx";
import { useDemoWorkflow } from "../hooks/useDemoWorkflow.js";
import { getCase, manualReporting, renderForm, renderUrl, downloadRenderUrl } from "../api/signal.js";
import "../styles/reporting-form.css";

const FORM_ID = "TX_MEASLES_OUTBREAK_CRF_2025";
const FORM_VERSION = "2025-05-07";

function responseData(response) {
  return response?.data || response;
}

function text(value) {
  return value === null || value === undefined || value === "" ? "Not recorded" : String(value);
}

export default function ReportingFormPage() {
  const { patientId: routePatientId, caseId = "" } = useParams();
  const navigate = useNavigate();
  const demo = useDemoWorkflow(caseId);
  const [caseData, setCaseData] = useState(null);
  const [manualPackage, setManualPackage] = useState(null);
  const [renderResult, setRenderResult] = useState(null);
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);
  const [operation, setOperation] = useState("");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  useEffect(() => {
    let active = true;
    setLoading(true);
    setError("");
    getCase(caseId)
      .then((result) => {
        if (active) setCaseData(responseData(result));
      })
      .catch((requestError) => {
        if (active) setError(requestError?.message || "Unable to load the reporting case.");
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => { active = false; };
  }, [caseId]);

  const patient = caseData?.patient || {};
  const actualPatientId = routePatientId || patient.patient_id || caseData?.patient_id || "";
  const caseWorkspacePath = actualPatientId
    ? `/patients/${encodeURIComponent(actualPatientId)}/case/${encodeURIComponent(caseId)}`
    : `/cases/${encodeURIComponent(caseId)}`;
  const submissionPath = actualPatientId
    ? `${caseWorkspacePath}/submission`
    : `/submissions/case/${encodeURIComponent(caseId)}`;
  const renderId = renderResult?.render_id || null;
  const previewUrl = renderId ? renderUrl(renderId) : "";
  const downloadUrl = renderId ? downloadRenderUrl(renderId) : "";
  const isDemoData = (renderResult?.fields || []).some(
    (field) => String(field?.source || "").toUpperCase() === "DEMO_DATA",
  );
  const technicalDetails = useMemo(() => ({
    case_id: renderResult?.case_id || manualPackage?.case_id || caseId,
    form_id: renderResult?.form_id || manualPackage?.form_id || FORM_ID,
    form_version: renderResult?.form_version || manualPackage?.form_version || FORM_VERSION,
    status: renderResult?.status || manualPackage?.status || "NOT_GENERATED",
    render_id: renderResult?.render_id || null,
    report_id: renderResult?.report_id || null,
    populated_fields: renderResult?.populated_fields || [],
    missing_fields: renderResult?.missing_fields || manualPackage?.missing_fields || [],
    warnings: [...(manualPackage?.warnings || []), ...(renderResult?.warnings || [])],
    field_sources: (renderResult?.fields || []).map(({ field, source, status }) => ({ field, source, status })),
  }), [caseId, manualPackage, renderResult]);

  async function generateForm() {
    if (!caseData || working) return;
    setWorking(true);
    setOperation("preparing");
    setError("");
    setMessage("");
    setManualPackage(null);
    setRenderResult(null);
    try {
      const preparation = responseData(await manualReporting(caseId, "FORM", ""));
      setManualPackage(preparation);

      setOperation("rendering");
      const rendered = responseData(await renderForm(caseId, {
        form_id: preparation?.form_id || FORM_ID,
        form_version: preparation?.form_version || FORM_VERSION,
        report_data: preparation?.report_data || {},
      }));
      if (!rendered?.render_id) {
        throw new Error("The backend did not return a render ID for the generated PDF.");
      }

      setRenderResult(rendered);
      demo.complete("reporting");
      setMessage("The Texas Measles form was generated by SIGNAL. Review the PDF before continuing.");
    } catch (requestError) {
      setError(requestError?.message || "Unable to generate the Texas Measles reporting form.");
    } finally {
      setWorking(false);
      setOperation("");
    }
  }

  if (loading) {
    return <section className="reporting-form-page"><SignalLoading title="Preparing Reporting Form" message="Loading the Texas Measles reporting information." /></section>;
  }

  if (!caseData) {
    return (
      <section className="reporting-form-page">
        <div className="reporting-form-error" role="alert">
          <h2>Unable to load reporting case</h2>
          <p>{error || "The requested case could not be loaded."}</p>
          <button type="button" className="button" onClick={() => navigate(routePatientId ? `/patients/${encodeURIComponent(routePatientId)}` : "/cases")}>Back</button>
        </div>
      </section>
    );
  }

  return (
    <section className="reporting-form-page">
      <header className="reporting-form-header">
        <div>
          <button type="button" className="reporting-form-back" onClick={() => navigate(caseWorkspacePath)}>← Back to Case Workspace</button>
          <span className="reporting-form-eyebrow">TEXAS PUBLIC HEALTH REPORTING</span>
          <h1>Texas Measles Reporting Form</h1>
          <p>Generate and review the official backend-rendered form for this case.</p>
        </div>
        <div className="reporting-form-context-badges">
          <span>{text(caseData.jurisdiction)}</span>
          <span>{text(caseData.disease)}</span>
          <span>Case {String(caseData.case_id || caseId).slice(0, 12)}…</span>
        </div>
      </header>

      {working && (
        <SignalLoading
          title={operation === "preparing" ? "Preparing Reporting Form" : "Rendering Reporting Form"}
          message={operation === "preparing" ? "Preparing the report package from the persisted case." : "Rendering the Texas PDF from backend-mapped case data."}
        />
      )}
      {(error || message) && <div className={`reporting-form-message ${error ? "is-error" : "is-success"}`} role={error ? "alert" : "status"}>{error || message}</div>}

      <section className="reporting-form-metadata" aria-label="Form metadata">
        <div><span>FORM</span><strong>Texas Measles Outbreak Case Report Form</strong></div>
        <div><span>FORM ID</span><strong>{renderResult?.form_id || manualPackage?.form_id || FORM_ID}</strong></div>
        <div><span>VERSION</span><strong>{renderResult?.form_version || manualPackage?.form_version || FORM_VERSION}</strong></div>
        <div><span>STATUS</span><strong className={renderResult ? "is-generated" : "is-pending"}>{renderResult ? "Generated by SIGNAL" : "Not generated"}</strong></div>
      </section>

      {((manualPackage?.missing_fields?.length || 0) > 0
        || (manualPackage?.warnings?.length || 0) > 0
        || (renderResult?.missing_fields?.length || 0) > 0
        || (renderResult?.warnings?.length || 0) > 0) && (
        <section className="reporting-form-notices" aria-label="Backend preparation notes">
          {[...(manualPackage?.missing_fields || []), ...(renderResult?.missing_fields || [])].length > 0 && <div><strong>Missing report data</strong><ul>{[...new Set([...(manualPackage?.missing_fields || []), ...(renderResult?.missing_fields || [])])].map((field) => <li key={field}>{field}</li>)}</ul></div>}
          {[...(manualPackage?.warnings || []), ...(renderResult?.warnings || [])].length > 0 && <div><strong>Backend warnings</strong><ul>{[...new Set([...(manualPackage?.warnings || []), ...(renderResult?.warnings || [])])].map((warning, index) => <li key={`${index}-${warning}`}>{warning}</li>)}</ul></div>}
        </section>
      )}

      {isDemoData && <div className="reporting-form-demo"><strong>DEMO DATA</strong><span>The backend marked one or more rendered values as demo data.</span></div>}

      <section className="reporting-form-pdf-card">
        <header className="reporting-form-card-header">
          <div>
            <span>FORM PREVIEW</span>
            <h2>Generated Texas Measles Form</h2>
            <p>{renderId ? `Render ID: ${renderId}` : "Generate the form to preview the PDF created by the SIGNAL backend."}</p>
          </div>
          {renderResult && <span className="reporting-form-rendered-badge">PDF generated</span>}
        </header>

        {renderId ? (
          <div className="reporting-form-pdf-frame">
            <iframe src={previewUrl} title="Texas Measles Reporting Form" className="reporting-form-pdf-viewer" />
          </div>
        ) : (
          <div className="reporting-form-pdf-empty">
            <strong>No generated PDF yet</strong>
            <span>The backend-generated Texas form will appear here after generation.</span>
          </div>
        )}

        <div className="reporting-form-actions">
          <button type="button" className="button button-primary" onClick={generateForm} disabled={working}>
            {working ? "Generating…" : "Generate Form"}
          </button>
          {renderId && <>
            <a className="button" href={previewUrl} target="_blank" rel="noreferrer">Open PDF</a>
            <a className="button" href={downloadUrl}>Download PDF</a>
          </>}
        </div>
      </section>

      <details className="reporting-form-technical">
        <summary>Technical Details</summary>
        <pre>{JSON.stringify(technicalDetails, null, 2)}</pre>
      </details>

      <footer className="reporting-form-next-step">
        <div>
          <span>NEXT WORKFLOW STEP</span>
          <strong>Review the generated PDF, then continue to Submission</strong>
          <p>PDF generation does not complete validation, human review, attestation, or submission. The backend workflow remains authoritative for each status.</p>
        </div>
        <button type="button" className="button button-primary" onClick={() => navigate(submissionPath)} disabled={!renderResult || working}>Continue to Submission</button>
      </footer>
    </section>
  );
}
